import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IsidroAntonio
 */
public class VentanaMatriz extends javax.swing.JFrame {
public DefaultTableModel Matriz;
public MatrizEntero MatrizCua;
public boolean realizarOperaciones;
    /**
     * Creates new form VentanaMatriz
     */
    public VentanaMatriz() {
        initComponents();
        Matriz=(DefaultTableModel)tblMatriz.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatriz = new javax.swing.JTable();
        txtTam = new javax.swing.JTextField();
        txtRen = new javax.swing.JTextField();
        btnMostrarTerminal = new javax.swing.JButton();
        btnInicializar = new javax.swing.JButton();
        txtCol = new javax.swing.JTextField();
        lblRen = new javax.swing.JLabel();
        lblTam = new javax.swing.JLabel();
        lblCol = new javax.swing.JLabel();
        btnSumaRen = new javax.swing.JButton();
        btnSumaCol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMatriz);

        btnMostrarTerminal.setText("Mostrar");
        btnMostrarTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTerminalActionPerformed(evt);
            }
        });

        btnInicializar.setText("Inicializar");
        btnInicializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicializarActionPerformed(evt);
            }
        });

        lblRen.setText("Renglones");

        lblTam.setText("Tamaño Matriz");

        lblCol.setText("Columnas");

        btnSumaRen.setText("Suma renglones");
        btnSumaRen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaRenActionPerformed(evt);
            }
        });

        btnSumaCol.setText("Suma columnas");
        btnSumaCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaColActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTam, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txtRen)
                            .addComponent(txtCol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSumaRen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInicializar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSumaCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblRen)
                    .addComponent(lblTam)
                    .addComponent(lblCol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrarTerminal)
                .addGap(299, 299, 299))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInicializar))
                        .addGap(18, 18, 18)
                        .addComponent(lblRen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSumaRen))
                        .addGap(20, 20, 20)
                        .addComponent(lblCol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSumaCol))))
                .addGap(29, 29, 29)
                .addComponent(btnMostrarTerminal)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTerminalActionPerformed
        MostrarMatrizTerminal();
    }//GEN-LAST:event_btnMostrarTerminalActionPerformed

    private void btnInicializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicializarActionPerformed
        int cua=0;
        try {
            cua = Integer.parseInt(txtTam.getText());
            MatrizCua = new MatrizEntero(cua);
        } catch (NumberFormatException e) {
            showMessageDialog(this, "Solo ingresa numeros");
            return;
        }

        Matriz.setColumnCount(MatrizCua.getTam());
        Matriz.setRowCount(MatrizCua.getTam());
        realizarOperaciones=true;
        MostrarMatriz();
        
    }//GEN-LAST:event_btnInicializarActionPerformed

    private void btnSumaRenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaRenActionPerformed
     if(realizarOperaciones){
         int ren=0;
         try {
              ren=Integer.parseInt(txtRen.getText());
              int resSumaRen=MatrizCua.sumarValoresRenglon(ren-1);
              showMessageDialog(this,"La suma de los valores del renglon "+ren+" es : "+resSumaRen);
          }catch (NumberFormatException e){
              showMessageDialog(this, "Ingresa el numero del renglon que deseas sumar");
               return;
          }
     }else{
         showMessageDialog(this,"No es posible realizar la operacion, primero genera una matriz");
     }
    }//GEN-LAST:event_btnSumaRenActionPerformed

    private void btnSumaColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaColActionPerformed
       if(realizarOperaciones){
         int col=0;
         try {
             col=Integer.parseInt(txtCol.getText());
              int resSumaCol=MatrizCua.sumarValoresColumna(col-1);
              showMessageDialog(this,"La suma de los valores de la columna "+col+" es : "+resSumaCol);
          }catch (NumberFormatException e){
              showMessageDialog(this, "Ingresa el numero de la columna que deseas sumar");
               return;
          }
     }else{
         showMessageDialog(this,"No es posible realizar la operacion, primero genera una matriz");
     }
    }//GEN-LAST:event_btnSumaColActionPerformed

    public void  MostrarMatrizTerminal() {
        for (int i = 0; i < MatrizCua.getTam(); i++) {
            for (int j = 0; j < MatrizCua.getTam(); j++) {
                System.out.print("");
                System.out.print("[" + MatrizCua.getMatriz()[i][j] + "] ");
            }//For interno
            System.out.println("");
        }//For externo
    }//Mostrar matriz en  terminal
    
    public void MostrarMatriz(){
        for (int i = 0; i < MatrizCua.getTam(); i++) {
            for (int j = 0; j < MatrizCua.getTam(); j++) {
                Matriz.setValueAt(MatrizCua.getMatriz()[i][j], i, j);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicializar;
    private javax.swing.JButton btnMostrarTerminal;
    private javax.swing.JButton btnSumaCol;
    private javax.swing.JButton btnSumaRen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCol;
    private javax.swing.JLabel lblRen;
    private javax.swing.JLabel lblTam;
    private javax.swing.JTable tblMatriz;
    private javax.swing.JTextField txtCol;
    private javax.swing.JTextField txtRen;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
